---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by littlefogcat.
---

print("sc1")

_G = {}

foo = function()
    print("modified!")
end
foo()

--observable = luajava.newInstance("top.littlefogcat.demolist.luaj.avoidoverride.Observable")
--
--callback = function()
--    --print("sc1 callback")
--    --foo()
--end
--
--foo = function()
--    print("modified!")
--end
--
--function hello()
--    print("hello")
--end
--
--observable:observe("sc1", callback)