---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by littlefogcat.
--- DateTime: 2021/6/1 11:42
---

clazz = luajava.bindClass "top.littlefogcat.demolist.luaj.threads.Observable"

clazz:run(nil)